apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
    - port: 5432
      name: postgres
  clusterIP: None
  selector:
    app: postgres

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: db_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: db_password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: db_name
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
          livenessProbe:
            initialDelaySeconds: 5
            exec:
              command: [ "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}" ]
          readinessProbe:
            initialDelaySeconds: 5
            exec:
              command: [ "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}" ]
  volumeClaimTemplates:
    - metadata:
        name: pgdata
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi

---

apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
spec:
  template:
    spec:
      containers:
        - name: migrate
          image: docker.io/andytakker/simple_server:latest
          env:
            - name: APP_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: db_user
            - name: APP_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: db_password
            - name: APP_DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: db_name
            - name: APP_DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: configs
                  key: db_host
            - name: APP_DATABASE_PORT
              value: "5432"
          command: ["/app/migrate.bin"]
      restartPolicy: OnFailure
